import { GoogleGenerativeAI } from '@google/generative-ai';

export interface IEmbeddingProvider {
  /**
   * Generates an embedding for the given text.
   * @param text The text to embed
   * @returns Array of numbers representing the embedding vector
   */
  generateEmbedding(text: string): Promise<number[]>;
  
  /**
   * Retrieves the dimension of the embedding generated by this provider
   */
  getDimension(): number;
  
  /**
   * Gets the provider/model name
   */
  getModelName(): string;
}

export class GeminiEmbeddingProvider implements IEmbeddingProvider {
  private genAI: GoogleGenerativeAI;
  private model: any;
  private dimension = 768; // V2 Pilot dimension
  private modelName = 'gemini-embedding-001';

  constructor(apiKey?: string) {
    const key = apiKey || process.env.GEMINI_API_KEY;
    if (!key) {
      throw new Error('GEMINI_API_KEY environment variable is required');
    }
    this.genAI = new GoogleGenerativeAI(key);
    this.model = this.genAI.getGenerativeModel({ model: this.modelName });
  }

  async generateEmbedding(text: string): Promise<number[]> {
    if (!text || text.trim() === '') {
      throw new Error('Text to embed cannot be empty');
    }
    
    // Quick retry logic for transient API issues
    let retries = 3;
    while (retries > 0) {
      try {
        const result = await this.model.embedContent(text);
        const vals = result.embedding.values;
        if (vals.length > this.dimension) {
          return vals.slice(0, this.dimension);
        }
        return vals;
      } catch (e: any) {
        retries--;
        if (retries === 0) throw new Error(`Gemini embedding failed: ${e.message}`);
        await new Promise(resolve => setTimeout(resolve, 1000));
      }
    }
    return [];
  }

  getDimension(): number {
    return this.dimension;
  }

  getModelName(): string {
    return this.modelName;
  }
}

// Contract prepared for future implementation
export class OpenAIEmbeddingProvider implements IEmbeddingProvider {
  constructor() {
    throw new Error('OpenAI provider not yet implemented');
  }
  
  async generateEmbedding(text: string): Promise<number[]> {
    throw new Error('Method not implemented.');
  }

  getDimension(): number {
    throw new Error('Method not implemented.');
  }

  getModelName(): string {
    throw new Error('Method not implemented.');
  }
}
