-- Harden the Data API boundary used by the private territorial beta.
-- This migration targets the already deployed schema directly and does not
-- depend on the historical migration chain being replayable.

begin;

do $block$
begin
  if not exists (
    select 1
    from pg_catalog.pg_roles
    where rolname = 'postgres'
      and rolbypassrls
  ) then
    raise exception 'postgres must have BYPASSRLS for the membership helper';
  end if;

  if not exists (
    select 1
    from pg_catalog.pg_roles
    where rolname = 'service_role'
      and rolbypassrls
  ) then
    raise exception 'service_role must have BYPASSRLS for server operations';
  end if;
end;
$block$;

-- Avoid recursive RLS evaluation through organization_members. The function
-- returns information only about the caller's own membership, uses fully
-- qualified objects, and is intentionally unavailable to anon.
create or replace function public.urbanbrain_can_access_expediente(
  target_expediente_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select
    (select auth.uid()) is not null
    and exists (
      select 1
      from public.expedientes as e
      inner join public.organization_members as om
        on om.org_id = e.org_id
      where e.id = target_expediente_id
        and om.profile_id = (select auth.uid())
    );
$function$;

alter function public.urbanbrain_can_access_expediente(uuid) owner to postgres;
revoke all privileges on function public.urbanbrain_can_access_expediente(uuid) from public;
revoke all privileges on function public.urbanbrain_can_access_expediente(uuid) from anon;
grant execute on function public.urbanbrain_can_access_expediente(uuid)
  to authenticated, service_role;

alter table public.chat_messages enable row level security;
alter table public.chat_messages force row level security;
alter table public.context_detections enable row level security;
alter table public.context_detections force row level security;
alter table public.expediente_afecciones enable row level security;
alter table public.expediente_afecciones force row level security;
alter table public.municipal_planning enable row level security;
alter table public.municipal_planning force row level security;
alter table public.afeccion_types enable row level security;
alter table public.afeccion_types force row level security;

-- Authorization roots are server-managed. Revoking their direct Data API
-- grants prevents membership or expediente escalation even if a permissive
-- historical policy exists in another environment.
alter table public.organizations enable row level security;
alter table public.organizations force row level security;
alter table public.profiles enable row level security;
alter table public.profiles force row level security;
alter table public.organization_members enable row level security;
alter table public.organization_members force row level security;
alter table public.expedientes enable row level security;
alter table public.expedientes force row level security;

-- RAG storage is not a browser API. V1 remains available through the RPC and
-- V2 through the server database connection only.
alter table public.normativa_chunks enable row level security;
alter table public.normativa_chunks force row level security;
alter table public.normative_documents_v2 enable row level security;
alter table public.normative_documents_v2 force row level security;
alter table public.normative_chunks_v2 enable row level security;
alter table public.normative_chunks_v2 force row level security;

-- Re-running the migration recreates only policies owned by this change.
drop policy if exists urbanbrain_chat_messages_select_tenant
  on public.chat_messages;
drop policy if exists urbanbrain_chat_messages_insert_self
  on public.chat_messages;
drop policy if exists urbanbrain_context_detections_select_tenant
  on public.context_detections;
drop policy if exists urbanbrain_expediente_afecciones_select_tenant
  on public.expediente_afecciones;
drop policy if exists urbanbrain_municipal_planning_select_authenticated
  on public.municipal_planning;
drop policy if exists urbanbrain_afeccion_types_select_authenticated
  on public.afeccion_types;

-- Chat history is tenant-readable. All writes remain server-only because the
-- webapp sends messages through /api/chat after the centralized access guard.
create policy urbanbrain_chat_messages_select_tenant
on public.chat_messages
for select
to authenticated
using (public.urbanbrain_can_access_expediente(expediente_id));

-- Territorial detections and applied constraints are generated by trusted
-- server processes. Authenticated users may read only their tenant rows.
create policy urbanbrain_context_detections_select_tenant
on public.context_detections
for select
to authenticated
using (public.urbanbrain_can_access_expediente(expediente_id));

create policy urbanbrain_expediente_afecciones_select_tenant
on public.expediente_afecciones
for select
to authenticated
using (public.urbanbrain_can_access_expediente(expediente_id));

-- municipal_planning is an explicit global catalogue: authenticated read-only,
-- never anonymously writable or readable through the Data API.
create policy urbanbrain_municipal_planning_select_authenticated
on public.municipal_planning
for select
to authenticated
using (true);

create policy urbanbrain_afeccion_types_select_authenticated
on public.afeccion_types
for select
to authenticated
using (true);

-- Remove broad default Data API grants, then grant the minimum surface.
revoke all privileges on table public.chat_messages
  from public, anon, authenticated;
revoke all privileges on table public.context_detections
  from public, anon, authenticated;
revoke all privileges on table public.expediente_afecciones
  from public, anon, authenticated;
revoke all privileges on table public.municipal_planning
  from public, anon, authenticated;
revoke all privileges on table public.afeccion_types
  from public, anon, authenticated;
revoke all privileges on table public.organizations
  from public, anon, authenticated;
revoke all privileges on table public.profiles
  from public, anon, authenticated;
revoke all privileges on table public.organization_members
  from public, anon, authenticated;
revoke all privileges on table public.expedientes
  from public, anon, authenticated;
revoke all privileges on table public.normativa_chunks
  from public, anon, authenticated;
revoke all privileges on table public.normative_documents_v2
  from public, anon, authenticated;
revoke all privileges on table public.normative_chunks_v2
  from public, anon, authenticated;

grant select on table public.chat_messages to authenticated;
grant select on table public.context_detections to authenticated;
grant select on table public.expediente_afecciones to authenticated;
grant select on table public.municipal_planning to authenticated;
grant select on table public.afeccion_types to authenticated;

grant select, insert, update, delete on table public.chat_messages
  to service_role;
grant select, insert, update, delete on table public.context_detections
  to service_role;
grant select, insert, update, delete on table public.expediente_afecciones
  to service_role;
grant select, insert, update, delete on table public.municipal_planning
  to service_role;
grant select, insert, update, delete on table public.afeccion_types
  to service_role;
grant select, insert, update, delete on table public.organizations
  to service_role;
grant select, insert, update, delete on table public.profiles
  to service_role;
grant select, insert, update, delete on table public.organization_members
  to service_role;
grant select, insert, update, delete on table public.expedientes
  to service_role;
grant select, insert, update, delete on table public.normativa_chunks
  to service_role;
grant select, insert, update, delete on table public.normative_documents_v2
  to service_role;
grant select, insert, update, delete on table public.normative_chunks_v2
  to service_role;

-- The webapp calls this RPC only from /api/chat with SUPABASE_SERVICE_ROLE_KEY.
-- Fail closed if the audited signature is not present or is ambiguous.
do $block$
declare
  rpc_count integer;
  rpc_signature regprocedure;
begin
  select count(*), (array_agg(p.oid))[1]::regprocedure
    into rpc_count, rpc_signature
  from pg_catalog.pg_proc as p
  inner join pg_catalog.pg_namespace as n
    on n.oid = p.pronamespace
  where n.nspname = 'public'
    and p.proname = 'match_normativa_chunks'
    and pg_catalog.pg_get_function_identity_arguments(p.oid)
      = 'query_embedding vector, match_count integer, filter_municipio text';

  if rpc_count <> 1 then
    raise exception
      'Expected exactly one public.match_normativa_chunks(vector, integer, text); found %',
      rpc_count;
  end if;

  execute format('alter function %s security invoker', rpc_signature);
  execute format(
    'alter function %s set search_path to pg_catalog, public, extensions',
    rpc_signature
  );
  execute format(
    'revoke all privileges on function %s from public',
    rpc_signature
  );
  execute format(
    'revoke all privileges on function %s from anon, authenticated',
    rpc_signature
  );
  execute format(
    'grant execute on function %s to service_role',
    rpc_signature
  );
end;
$block$;

commit;
